export const movies = ['All Movies', 'Chucky', 'Halloween', 'Scream', 'Midsommar', 'Five Nights at Freddy\'s', 'A24 Horror'];

export const questions = [
  { id: 'chucky-1', movie: 'Chucky', difficulty: 1, q: 'In Child\'s Play, what is the real name of the killer whose soul ends up inside the Good Guy doll?', choices: ['Charles Lee Ray', 'Eddie Caputo', 'Mike Norris', 'Andy Barclay'], answer: 'Charles Lee Ray' },
  { id: 'chucky-2', movie: 'Chucky', difficulty: 1, q: 'What is the name of the young boy who receives Chucky as a birthday gift?', choices: ['Tommy Doyle', 'Andy Barclay', 'Billy Loomis', 'Garrett Schmidt'], answer: 'Andy Barclay' },
  { id: 'chucky-3', movie: 'Chucky', difficulty: 2, q: 'Which phrase is part of Chucky\'s Good Guy doll introduction?', choices: ['Hi, I\'m Chucky, wanna play?', 'Do you like scary movies?', 'The night he came home', 'This is my design'], answer: 'Hi, I\'m Chucky, wanna play?' },
  { id: 'chucky-4', movie: 'Chucky', difficulty: 2, q: 'What does Chucky need Andy for after transferring into the doll?', choices: ['To transfer his soul into the first person he revealed himself to', 'To hide the doll box', 'To find a new Good Guy factory', 'To repair his batteries'], answer: 'To transfer his soul into the first person he revealed himself to' },
  { id: 'chucky-5', movie: 'Chucky', difficulty: 3, q: 'Who investigates the strange deaths around Andy and eventually learns the doll may be alive?', choices: ['Detective Mike Norris', 'Dr. Loomis', 'Dewey Riley', 'Officer Hawkins'], answer: 'Detective Mike Norris' },

  { id: 'halloween-1', movie: 'Halloween', difficulty: 1, q: 'What is the name of the masked killer in Halloween?', choices: ['Michael Myers', 'Jason Voorhees', 'Freddy Krueger', 'Billy Loomis'], answer: 'Michael Myers' },
  { id: 'halloween-2', movie: 'Halloween', difficulty: 1, q: 'Who is the babysitter Michael Myers stalks on Halloween night?', choices: ['Laurie Strode', 'Sidney Prescott', 'Dani Ardor', 'Karen Barclay'], answer: 'Laurie Strode' },
  { id: 'halloween-3', movie: 'Halloween', difficulty: 2, q: 'What town is central to the original Halloween story?', choices: ['Haddonfield', 'Woodsboro', 'Springwood', 'Crystal Lake'], answer: 'Haddonfield' },
  { id: 'halloween-4', movie: 'Halloween', difficulty: 2, q: 'What doctor repeatedly warns people about Michael Myers?', choices: ['Dr. Sam Loomis', 'Dr. Hill', 'Dr. Gordon', 'Dr. Wynn'], answer: 'Dr. Sam Loomis' },
  { id: 'halloween-5', movie: 'Halloween', difficulty: 3, q: 'In the 1978 film, what happens after Loomis shoots Michael off the balcony?', choices: ['Michael disappears from the ground below', 'Michael is arrested in the yard', 'Laurie removes his mask', 'The police burn the house'], answer: 'Michael disappears from the ground below' },

  { id: 'scream-1', movie: 'Scream', difficulty: 1, q: 'What is the killer\'s phone question that opens Scream\'s horror-game vibe?', choices: ['What\'s your favorite scary movie?', 'Do you want to play a game?', 'Can you hear the lambs?', 'Where is Woodsboro High?'], answer: 'What\'s your favorite scary movie?' },
  { id: 'scream-2', movie: 'Scream', difficulty: 1, q: 'Who is the main final girl of the Scream series?', choices: ['Sidney Prescott', 'Gale Weathers', 'Tatum Riley', 'Casey Becker'], answer: 'Sidney Prescott' },
  { id: 'scream-3', movie: 'Scream', difficulty: 2, q: 'What is the fictional town where the original Scream takes place?', choices: ['Woodsboro', 'Haddonfield', 'Ambrose', 'Santa Carla'], answer: 'Woodsboro' },
  { id: 'scream-4', movie: 'Scream', difficulty: 2, q: 'Which two characters are revealed as the original Ghostface killers?', choices: ['Billy Loomis and Stu Macher', 'Dewey Riley and Randy Meeks', 'Cotton Weary and Neil Prescott', 'Mickey and Roman'], answer: 'Billy Loomis and Stu Macher' },
  { id: 'scream-5', movie: 'Scream', difficulty: 3, q: 'What horror rule does Randy emphasize about surviving a scary movie?', choices: ['Never say you\'ll be right back', 'Always split up', 'Open every basement door', 'Trust the boyfriend immediately'], answer: 'Never say you\'ll be right back' },

  { id: 'midsommar-1', movie: 'Midsommar', difficulty: 1, q: 'Where do Dani and the group travel for the midsummer festival?', choices: ['Sweden', 'Norway', 'Iceland', 'Finland'], answer: 'Sweden' },
  { id: 'midsommar-2', movie: 'Midsommar', difficulty: 1, q: 'Who is Dani\'s boyfriend in Midsommar?', choices: ['Christian', 'Pelle', 'Josh', 'Mark'], answer: 'Christian' },
  { id: 'midsommar-3', movie: 'Midsommar', difficulty: 2, q: 'What title does Dani win near the end of the festival?', choices: ['May Queen', 'Harvest Bride', 'Sun Mother', 'Flower Saint'], answer: 'May Queen' },
  { id: 'midsommar-4', movie: 'Midsommar', difficulty: 2, q: 'What makes Midsommar visually unusual for a horror movie?', choices: ['Most of the horror happens in bright daylight', 'It is filmed entirely underwater', 'It has no human characters', 'It takes place only in winter darkness'], answer: 'Most of the horror happens in bright daylight' },
  { id: 'midsommar-5', movie: 'Midsommar', difficulty: 3, q: 'What disturbing ritual occurs early in the Harga festival involving two elders?', choices: ['Attestupa cliff sacrifice', 'A midnight mirror trial', 'A masked corn maze hunt', 'A doll possession ceremony'], answer: 'Attestupa cliff sacrifice' },

  { id: 'fnaf-1', movie: 'Five Nights at Freddy\'s', difficulty: 1, q: 'What job does Mike take at Freddy Fazbear\'s Pizza?', choices: ['Night security guard', 'Animatronic engineer', 'Restaurant manager', 'Police detective'], answer: 'Night security guard' },
  { id: 'fnaf-2', movie: 'Five Nights at Freddy\'s', difficulty: 1, q: 'What is the name of Mike\'s younger sister in the 2023 movie?', choices: ['Abby', 'Vanessa', 'Cassie', 'Susie'], answer: 'Abby' },
  { id: 'fnaf-3', movie: 'Five Nights at Freddy\'s', difficulty: 2, q: 'Which animatronic is the bear mascot of the restaurant?', choices: ['Freddy Fazbear', 'Bonnie', 'Foxy', 'Chica'], answer: 'Freddy Fazbear' },
  { id: 'fnaf-4', movie: 'Five Nights at Freddy\'s', difficulty: 2, q: 'Who is the police officer who helps Mike understand the restaurant\'s past?', choices: ['Vanessa', 'Aunt Jane', 'Max', 'Kim'], answer: 'Vanessa' },
  { id: 'fnaf-5', movie: 'Five Nights at Freddy\'s', difficulty: 3, q: 'What phrase is closely tied to William Afton\'s reveal and survival?', choices: ['I always come back', 'Wanna play?', 'Do you like scary movies?', 'The night he came home'], answer: 'I always come back' },

  { id: 'a24-1', movie: 'A24 Horror', difficulty: 1, q: 'Which director made Hereditary and Midsommar for A24?', choices: ['Ari Aster', 'Robert Eggers', 'Ti West', 'Alex Garland'], answer: 'Ari Aster' },
  { id: 'a24-2', movie: 'A24 Horror', difficulty: 1, q: 'Which A24 horror film follows a Puritan family slowly breaking apart near a forbidden forest?', choices: ['The Witch', 'X', 'Talk to Me', 'Pearl'], answer: 'The Witch' },
  { id: 'a24-3', movie: 'A24 Horror', difficulty: 1, q: 'In Talk to Me, what object lets characters contact spirits?', choices: ['An embalmed ceramic hand', 'A cursed videotape', 'A silver puzzle box', 'A wooden mask'], answer: 'An embalmed ceramic hand' },
  { id: 'a24-4', movie: 'A24 Horror', difficulty: 1, q: 'Which A24 film is a bright daylight folk-horror story about grief, belonging, and a Swedish commune?', choices: ['Midsommar', 'Hereditary', 'The Lighthouse', 'Green Room'], answer: 'Midsommar' },
  { id: 'a24-5', movie: 'A24 Horror', difficulty: 2, q: 'In Hereditary, what family tragedy becomes the emotional rupture that pushes the story into full occult horror?', choices: ['Charlie dies after the party accident', 'Peter vanishes into the woods', 'Annie burns the family photos', 'Steve inherits a haunted hotel'], answer: 'Charlie dies after the party accident' },
  { id: 'a24-6', movie: 'A24 Horror', difficulty: 2, q: 'What is the central setting of The Lighthouse, directed by Robert Eggers?', choices: ['An isolated lighthouse island', 'A haunted ballet academy', 'A desert gas station', 'A suburban grief group'], answer: 'An isolated lighthouse island' },
  { id: 'a24-7', movie: 'A24 Horror', difficulty: 2, q: 'In X, what type of production are the young characters secretly making at the rural farm?', choices: ['An adult film', 'A true-crime documentary', 'A ghost-hunting show', 'A religious broadcast'], answer: 'An adult film' },
  { id: 'a24-8', movie: 'A24 Horror', difficulty: 2, q: 'Which director is behind X, Pearl, and MaXXXine?', choices: ['Ti West', 'Jordan Peele', 'David Robert Mitchell', 'Panos Cosmatos'], answer: 'Ti West' },
  { id: 'a24-9', movie: 'A24 Horror', difficulty: 2, q: 'In Pearl, what dream pushes Pearl to resent her trapped farm life?', choices: ['She wants to become a movie star/dancer', 'She wants to become a police detective', 'She wants to open a funeral home', 'She wants to lead a cult'], answer: 'She wants to become a movie star/dancer' },
  { id: 'a24-10', movie: 'A24 Horror', difficulty: 2, q: 'What emotional idea does The Babadook-style A24-adjacent elevated horror often share with Hereditary and Midsommar?', choices: ['Grief can become the monster of the story', 'Technology always saves the characters', 'The villain must be supernatural only', 'Horror works best without family conflict'], answer: 'Grief can become the monster of the story' },
  { id: 'a24-11', movie: 'A24 Horror', difficulty: 3, q: 'In Hereditary, what demon/cult figure is the family being maneuvered toward serving?', choices: ['Paimon', 'Valak', 'Bughuul', 'Pazuzu'], answer: 'Paimon' },
  { id: 'a24-12', movie: 'A24 Horror', difficulty: 3, q: 'What makes the ending of Midsommar psychologically disturbing instead of just visually shocking?', choices: ['Dani smiles while being absorbed into the commune\'s ritual logic', 'Dani escapes and calls the police immediately', 'The entire trip is revealed as a dream', 'Christian becomes the new cult leader'], answer: 'Dani smiles while being absorbed into the commune\'s ritual logic' },
  { id: 'a24-13', movie: 'A24 Horror', difficulty: 3, q: 'In The Witch, what phrase marks Thomasin\'s final temptation into freedom and damnation?', choices: ['Wouldst thou like to live deliciously?', 'Do you like scary movies?', 'I always come back', 'Be my victim'], answer: 'Wouldst thou like to live deliciously?' },
  { id: 'a24-14', movie: 'A24 Horror', difficulty: 3, q: 'In Talk to Me, why does the hand become more dangerous the longer characters use it?', choices: ['They keep the spirit connection open too long', 'It runs out of batteries', 'It summons only vampires after midnight', 'It erases camera footage'], answer: 'They keep the spirit connection open too long' },
  { id: 'a24-15', movie: 'A24 Horror', difficulty: 3, q: 'What is the main psychological pressure in The Lighthouse?', choices: ['Isolation, power struggle, and possible madness between two keepers', 'A masked killer hunting a babysitter', 'A haunted doll chasing a child', 'A group solving a school mystery'], answer: 'Isolation, power struggle, and possible madness between two keepers' },
  { id: 'a24-16', movie: 'A24 Horror', difficulty: 3, q: 'In Men, directed by Alex Garland, what pattern makes Harper\'s countryside retreat feel surreal and threatening?', choices: ['Multiple men appear with the same face', 'Every mirror shows her childhood', 'The village has no daylight', 'Animals speak in riddles'], answer: 'Multiple men appear with the same face' },
  { id: 'a24-17', movie: 'A24 Horror', difficulty: 3, q: 'What does Saint Maud focus on as its main horror engine?', choices: ['Religious obsession and a nurse\'s unstable sense of divine purpose', 'A haunted animatronic restaurant', 'A masked killer calling teenagers', 'A cursed spaceship infection'], answer: 'Religious obsession and a nurse\'s unstable sense of divine purpose' },
  { id: 'a24-18', movie: 'A24 Horror', difficulty: 3, q: 'In Bodies Bodies Bodies, what is the story really attacking beneath the slasher-party setup?', choices: ['Paranoia, privilege, fake friendship, and social-media suspicion', 'Ancient witchcraft in colonial New England', 'A demon king taking a body', 'A haunted lighthouse curse'], answer: 'Paranoia, privilege, fake friendship, and social-media suspicion' },
  { id: 'a24-19', movie: 'A24 Horror', difficulty: 3, q: 'In Green Room, what makes the trapped punk band\'s situation so tense?', choices: ['They witness a murder at a violent neo-Nazi venue', 'They awaken a forest demon', 'They are hunted by animatronics', 'They are trapped in a time loop at prom'], answer: 'They witness a murder at a violent neo-Nazi venue' },
  { id: 'a24-20', movie: 'A24 Horror', difficulty: 3, q: 'Which answer best describes the A24 horror style this quiz is testing?', choices: ['Character trauma, symbolism, slow dread, and story meaning', 'Only jump scares with no plot', 'Mostly superhero battles', 'Only found-footage comedy'], answer: 'Character trauma, symbolism, slow dread, and story meaning' }
];
